version: "3"
services:
  db:
    image: postgres:13-alpine
    container_name: db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          memory: 512M
    ports:
      - ${DB_LOCAL_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django_db
    networks:
      - django-net

  web:
    image: django-backend:v1
    container_name: web
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          memory: 128M
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${WEB_LOCAL_PORT}:8000
    volumes:
      - static_data:/home/django/app/staticfiles
      - media_data:/home/django/app/mediafiles
    links:
      - db
    depends_on:
      - db
    environment:
      - ENVIRONMENT=docker
      - DB_HOST=db
      - DB_PORT=5432
    entrypoint: /home/django/app/entrypoint.sh
    networks:
      - django-net

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          memory: 128M
    depends_on:
      - web
    links:
      - web
    volumes:
      - ./envs/docker/default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/staticfiles
      - media_data:/mediafiles
    networks:
      - django-net
    ports:
      - ${NGINX_LOCAL_PORT}:80
    expose:
      - 80
  
volumes:
  static_data:
  media_data:
  postgres_data:

networks:
  django-net:
    driver: bridge